### ISSUE TITLE
Can't install on vercel (AWS) or GCP

### ISSUE THREAD

**Issue by sebnun** [albertxing/node-ffmpeg#1]
Hi, I'm having trouble deploying the library to vercel and GCP.

It fails on npm install step on vercel, here are the logs:
```
[13:46:51.976] Installing dependencies...
[13:47:00.787] npm ERR! code 1
[13:47:00.787] npm ERR! path /vercel/path0/node_modules/ffmpeg-native
[13:47:00.789] npm ERR! command failed
[13:47:00.790] npm ERR! command sh -c node-gyp-build
[13:47:00.790] npm ERR! make: Entering directory `/vercel/path0/node_modules/ffmpeg-native/build'
[13:47:00.790] npm ERR! make: Leaving directory `/vercel/path0/node_modules/ffmpeg-native/build'
[13:47:00.791] npm ERR! gyp info it worked if it ends with ok
[13:47:00.791] npm ERR! gyp info using node-gyp@9.3.1
[13:47:00.791] npm ERR! gyp info using node@18.16.1 | linux | x64
[13:47:00.792] npm ERR! gyp info find Python using Python version 3.9.8 found at "/usr/local/bin/python3"
[13:47:00.792] npm ERR! gyp http GET https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
[13:47:00.793] npm ERR! gyp http 200 https://nodejs.org/download/release/v18.16.1/node-v18.16.1-headers.tar.gz
[13:47:00.793] npm ERR! gyp http GET https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
[13:47:00.794] npm ERR! gyp http 200 https://nodejs.org/download/release/v18.16.1/SHASUMS256.txt
[13:47:00.794] npm ERR! gyp info spawn /usr/local/bin/python3
[13:47:00.794] npm ERR! gyp info spawn args [
[13:47:00.794] npm ERR! gyp info spawn args   '/node18/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
[13:47:00.794] npm ERR! gyp info spawn args   'binding.gyp',
[13:47:00.795] npm ERR! gyp info spawn args   '-f',
[13:47:00.795] npm ERR! gyp info spawn args   'make',
[13:47:00.795] npm ERR! gyp info spawn args   '-I',
[13:47:00.795] npm ERR! gyp info spawn args   '/vercel/path0/node_modules/ffmpeg-native/build/config.gypi',
[13:47:00.795] npm ERR! gyp info spawn args   '-I',
[13:47:00.795] npm ERR! gyp info spawn args   '/node18/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
[13:47:00.795] npm ERR! gyp info spawn args   '-I',
[13:47:00.796] npm ERR! gyp info spawn args   '/vercel/.cache/node-gyp/18.16.1/include/node/common.gypi',
[13:47:00.796] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
[13:47:00.796] npm ERR! gyp info spawn args   '-Dvisibility=default',
[13:47:00.796] npm ERR! gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/18.16.1',
[13:47:00.796] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/node18/lib/node_modules/npm/node_modules/node-gyp',
[13:47:00.797] npm ERR! gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/18.16.1/<(target_arch)/node.lib',
[13:47:00.797] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules/ffmpeg-native',
[13:47:00.797] npm ERR! gyp info spawn args   '-Dnode_engine=v8',
[13:47:00.797] npm ERR! gyp info spawn args   '--depth=.',
[13:47:00.797] npm ERR! gyp info spawn args   '--no-parallel',
[13:47:00.797] npm ERR! gyp info spawn args   '--generator-output',
[13:47:00.798] npm ERR! gyp info spawn args   'build',
[13:47:00.799] npm ERR! gyp info spawn args   '-Goutput_dir=.'
[13:47:00.799] npm ERR! gyp info spawn args ]
[13:47:00.799] npm ERR! gyp info spawn make
[13:47:00.800] npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
[13:47:00.800] npm ERR! make: *** No rule to make target `Release/obj.target/ffmpeg/src/node_ffmpeg.o', needed by `Release/obj.target/ffmpeg.node'.  Stop.
[13:47:00.800] npm ERR! gyp ERR! build error 
[13:47:00.800] npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
[13:47:00.801] npm ERR! gyp ERR! stack     at ChildProcess.onExit (/node18/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
[13:47:00.801] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
[13:47:00.801] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
[13:47:00.801] npm ERR! gyp ERR! System Linux 5.10.179-168.710.amzn2.x86_64
[13:47:00.801] npm ERR! gyp ERR! command "/node18/bin/node" "/node18/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[13:47:00.804] npm ERR! gyp ERR! cwd /vercel/path0/node_modules/ffmpeg-native
[13:47:00.804] npm ERR! gyp ERR! node -v v18.16.1
[13:47:00.804] npm ERR! gyp ERR! node-gyp -v v9.3.1
[13:47:00.805] npm ERR! gyp ERR! not ok
[13:47:00.805] 
[13:47:00.806] npm ERR! A complete log of this run can be found in:
[13:47:00.806] npm ERR!     /vercel/.npm/_logs/2023-06-30T11_46_52_453Z-debug-0.log
[13:47:00.834] Error: Command "npm install" exited with 1
[13:47:01.275] BUILD_UTILS_SPAWN_1: Command "npm install" exited with 1
```
and on deployment as a function to GCP

```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed with status: FAILURE and message: npm ERR! code 1
npm ERR! path /workspace/node_modules/ffmpeg-native
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! make: Entering directory '/workspace/node_modules/ffmpeg-native/build'
npm ERR! make: Leaving directory '/workspace/node_modules/ffmpeg-native/build'
npm ERR! make: *** No rule to make target 'Release/obj.target/ffmpeg/src/node_ffmpeg.o', needed by 'Release/obj.target/ffmpeg.node'.  Stop.
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.10.0-22-cloud-amd64
npm ERR! gyp ERR! command "/layers/google.nodejs.runtime/node/bin/node" "/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /workspace/node_modules/ffmpeg-native
npm ERR! gyp ERR! node -v v18.16.0
npm ERR! gyp ERR! node-gyp -v v9.3.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /www-data-home/.npm/_logs/2023-06-30T20_40_05_297Z-debug-0.log. For more details see the logs at https://console.cloud.google.com/cloud-build/builds;region=us-central1/c654d055-0d31-4ea3-8d6e-9d55b0f44ebd?project=204605999199.
```

Looks like it's not getting the proper rules to build it on linux? Any tips on how to fix this?

**Comment by albertxing** [comment]
Thanks for testing this @sebnun - unfortunately I haven't added Linux support yet. With Windows and macOS I have prebuilt modules from GitHub actions, but the package from npm _only_ includes prebuilds, and does not include source files, which is why node-gyp can't find the source files.

If you'd like to get a Linux build working yourself, try cloning the repo and building directly from source instead of using npm. You'll need to tweak build parameters in binding.gyp as well as the Makefile in src/libffmpeg
